"""create bookmark table

Revision ID: 1b04db1c24fd
Revises: 4eb831717e8d
Create Date: 2014-12-13 14:14:34.843688

"""

# revision identifiers, used by Alembic.
revision = '1b04db1c24fd'
down_revision = '4eb831717e8d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('list_media_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_account_id'), 'bookmark', ['account_id'], unique=False)
    op.create_index(op.f('ix_bookmark_list_media_id'), 'bookmark', ['list_media_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_list_media_id'), table_name='bookmark')
    op.drop_index(op.f('ix_bookmark_account_id'), table_name='bookmark')
    op.drop_table('bookmark')
    ### end Alembic commands ###
