"""create_account_connection_table

Revision ID: 5511a2d0efea
Revises: 90edc39ec78
Create Date: 2015-07-02 14:48:18.888494

"""

# revision identifiers, used by Alembic.
revision = '5511a2d0efea'
down_revision = '90edc39ec78'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=30), nullable=True),
    sa.Column('provider_user_id', sa.String(length=30), nullable=True),
    sa.Column('access_token', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('profile_url', sa.String(length=180), nullable=True),
    sa.Column('avatar_url', sa.String(length=180), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_connection')
    ### end Alembic commands ###
